### PR TITLE
README: add missing verb

### PR DESCRIPTION
**Pull request by waldyrious**
By the way, I didn't find a way to make this change from the gitbook-rendered version. Perhaps the README could end with a link to this repo?

### CODE REVIEW

**Comment by panathea** [comment]
Hey, much appreciated. I've added some GitHub links to the top of each page with plugins which should make contributing easier in the future. Look good to you?

**Comment by waldyrious** [comment]
You mean the "Edit this page" links? Those looks great, yeah :) I am not sure why they aren't part of gitbook's default interface -- how are people supposed to send contributions otherwise?

By the way, it would be helpful to add the link to the gitbook (and a small description) in the repository main page here on GitHub, for easy access to the gitbook. Currently it says "No description, website, or topics provided."

**Comment by panathea** [comment]
Yep, I definitely didn't spend any time setting this repo up -- added the link back. I'll probably need to purchase a domain to make everything look pretty but for now this will do. Thanks for your assistance.

Are you a Plover user?

**Comment by waldyrious** [comment]
> Are you a Plover user?

A prospective one :P haven't gotten around to actually dive into it, so for now I'm kind of tracking the project from the sidelines and helping out if I can.

**Pull request merged**
